spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webfinite
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB # 업로드 가능한 파일 크기 제한
      max-request-size: 10MB # 요청 크기 제한

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

server:
  tomcat:
    max-swallow-size: 10MB

logging:
  level:
    org:
      springframework: DEBUG
      hibernate.SQL: debug
    com:
      SOLUX_WEBFINITE_BE:
        webfinite_be: DEBUG
    org.hibernate.orm.jdbc.bind: trace # 스프링 부트 3.x, Hibernate 6

openai:
  model: gpt-4o
  key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1/chat/completions # gpt-4o 엔드포인트